#!/bin/bash 

for n in {1..3}
do
    hzn exchange node addpolicy -f policy-1-3.json dev$n
done

for n in {4..6} 
do
    hzn exchange node addpolicy -f policy-4-6.json dev$n
done

for n in {7..9} 
do
    hzn exchange node addpolicy -f policy-7-9.json dev$n
done

for n in {10..12} 
do
    hzn exchange node addpolicy -f policy-10-12.json dev$n
done

echo "Done."

